version: "3"

services:
  loki:
    image: grafana/loki:latest
    container_name: "loki"
    command: -config.file=/etc/loki/config.yaml
    volumes:
      - ./loki-config.yml:/etc/loki/config.yaml
    networks:
      - loki_internal
      - grafana_internal

  promtail:
    image: grafana/promtail:latest
    command: -config.file=/etc/promtail/config.yaml
    volumes:
      - ./promtail-config.yml:/etc/promtail/config.yaml
      - /var/log:/var/log
    networks:
      - loki_internal

networks:
  loki_internal:
    external: true
  grafana_internal:
    external: true