version: "3.8"

services:

    node-exporter:
    image: "prom/node-exporter:latest"
    container_name: "node-exporter"
    command: 
      - "--web.config=\"web-config.yml\""
    volumes:
      - "./web-config.yml:./web-config.yml"
    restart: always
    networks:
      - prometheus_internal

networks:
  prometheus_internal:
    external: true