# my global config
global:
  scrape_interval: 15s

scrape_configs:
- job_name: prometheus
  static_configs:
  - targets: ["localhost:9090", "localhost:9191"]
  
- job_name: localhost_node
  static_configs:
  - targets: ["node-exporter:9100"]
    labels:
      instance: "local_server"