[api]
  dashboard = true
  insecure = false
[ping]

[log]
  level = "INFO"

[providers]
  [providers.docker]
    exposedbydefault = false
  [providers.file]
    directory = "/etc/traefik/conf"

[entryPoints]
  [entryPoints.web]
    address = ":80"

    [entryPoints.web.http]
      [entryPoints.web.http.redirections]
        [entryPoints.web.http.redirections.entryPoint]
          to = "websecure"
          scheme = "https"

  [entryPoints.websecure]
    address = ":443"


[certificatesResolvers.myresolver.acme]
  email = "w@shoujo.network"
  storage = "/letsencrypt/acme.json"
  [certificatesResolvers.myresolver.acme.httpChallenge]
    entryPoint = "web"
  [certificatesResolvers.myresolver.acme.tlsChallenge]
  [certificatesResolvers.myresolver.acme.dnsChallenge]
    provider = "cloudflare"
    delayBeforeCheck = 0