version: "3.8"

services:

  grafana:
    image: "grafana/grafana:latest"
    container_name: "grafana"
    volumes:
      - "grafana_data:/var/lib/grafana"
      - "./grafana.ini:/etc/grafana/grafana.ini"
    restart: always
    networks:
      - traefik_net
      - grafana_internal
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.rule=Host(`${HOST}`)"
      - "traefik.http.routers.grafana.middlewares=global-compress@file"
      - "traefik.http.routers.grafana.entrypoints=websecure"
      - "traefik.http.routers.grafana.tls=true"
      - "traefik.http.routers.grafana.tls.certresolver=myresolver"

volumes:
  grafana_data:

networks:
  traefik_net:
    external: true
  grafana_internal:
    external: true