version: "3.8"

services:

  portainer:
    image: "portainer/portainer:alpine"
    container_name: "portainer"
    ports: 
      - "8000:8000"
    volumes:
      - "portainer_data:/data"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    restart: always
    networks:
      - traefik_net
    labels:
      - "traefik.enable=true"
      #- "traefik.docker.network=portainer"
      - "traefik.http.routers.portainer.rule=Host(${HOST})"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"
      - "traefik.http.routers.portainer.middlewares=global-compress@file"
      - "traefik.http.routers.portainer.entrypoints=websecure"
      - "traefik.http.routers.portainer.tls=true"
      - "traefik.http.routers.portainer.tls.certresolver=myresolver"

volumes:
  portainer_data:

networks:
  traefik_net:
    external: true