version: "3.8"

services:

  portainer:
    image: "portainer/portainer:alpine"
    container_name: "portainer"
    volumes:
      - "portainer_data:/data"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.rule=Host(`${HOST}`)"
      - "traefik.http.routers.portainer.service.loadbalancer.server.port=9000"
      - "traefik.http.routers.portainer.middlewares=global-compress@file"
      - "traefik.http.routers.portainer.entrypoints=websecure"
      - "traefik.http.routers.portainer.tls.certresolver=myresolver"
      
volumes:
  portainer_data: