version: "3"

services:

  portainer-agent:
    image: "portainer/agent:latest"
    ports: 
      - "9001:9001"
    environment: 
      EDGE: 1
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/var/lib/docker/volumes:/var/lib/docker/volumes:ro"
      - "/:/host:ro"
    restart: always