version: "3"

services:

  portainer-agent:
    image: "portainer/agent:latest"
    environment: 
      EDGE: 1
      EDGE_ID: e98c21dd-4e39-412b-ba26-d150f1892691
      EDGE_KEY: aHR0cHM6Ly9vcmlnaW4tcG9ydGFpbmVyLnNob3Vqby5uZXR3b3JrfG9yaWdpbi1wb3J0YWluZXIuc2hvdWpvLm5ldHdvcms6ODAwMHwyNTpiMzpjYzo4NTpkMDo4MjplOTpjMzo0YTphOTplODozYzo4ODo3MDo1ZjpjMnwyNw
      CAP_HOST_MANAGEMENT: 1
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/var/lib/docker/volumes:/var/lib/docker/volumes"
      - "/:/host"
      - portainer_agent_data:/data
    restart: always

volumes: 
  portainer_agent_data: